plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'me.rightsflow'
version = '0.0.1-SNAPSHOT'
description = 'RightsFlow Gateway Server'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springCloudVersion', "2025.0.0")
    set('micrometerVersion', "1.5.5")
	name = 'RightsFlow Gateway Server'
	sourceEncoding='UTF-8'
}

dependencies {

    implementation(platform("io.micrometer:micrometer-tracing-bom:${micrometerVersion}"))

	// Spring Boot Starters
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	//implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	//implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Spring Cloud
	implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	implementation 'org.springframework.cloud:spring-cloud-starter-config'
	implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
	implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'

	// Security
	implementation 'org.springframework.security:spring-security-oauth2-jose'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	//implementation 'org.springframework.security:spring-security-oauth2-resource-server'

	// Rate Limiting
	implementation 'io.github.resilience4j:resilience4j-ratelimiter'
	implementation 'io.github.resilience4j:resilience4j-reactor'
	//implementation 'io.github.resilience4j:resilience4j-spring-boot3'

    // "Мост" между Micrometer (API метрик) и Prometheus (система мониторинга)
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // Structured Logging
    implementation 'net.logstash.logback:logstash-logback-encoder:8.1'

    // Micrometer Tracing
    implementation 'io.micrometer:micrometer-tracing'
    implementation 'io.micrometer:micrometer-observation'
    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'

    implementation 'io.micrometer:context-propagation'
    implementation 'io.projectreactor:reactor-core-micrometer'

    // Caching
	implementation 'com.github.ben-manes.caffeine:caffeine'

    // JWT
	implementation 'com.nimbusds:nimbus-jose-jwt:9.37.3'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'io.projectreactor:reactor-test'
	testImplementation 'org.mockito:mockito-core'
	testImplementation 'org.testcontainers:junit-jupiter'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

bootJar {
	archiveBaseName = 'rf-gateway-svc'
	archiveVersion = ''  // Убираем версию из имени файла
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs.add('-parameters')
}

bootRun {
	systemProperties = System.properties as Map<String, ?>
}